#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Thu Sep 19 20:48:04 2024

add_design "F:/FPGA/SME309/lab1/project/control.v"
add_design "F:/FPGA/SME309/lab1/project/control_tb.v"
add_design "F:/FPGA/SME309/lab1/project/mem.v"
add_design "F:/FPGA/SME309/lab1/project/Seven_Seg.v"
add_design "F:/FPGA/SME309/lab1/project/top.v"
remove_design -verilog "F:/FPGA/SME309/lab1/project/control_tb.v"
add_design "F:/FPGA/SME309/lab1/project/control_tb.v"
remove_design -verilog "F:/FPGA/SME309/lab1/project/control_tb.v"
add_simulation "F:/FPGA/SME309/lab1/project/control_tb.v"
