#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Thu Oct 17 19:18:00 2024

add_simulation "F:/SME_files/SME309/codes/SME209_codes/lab2/PDS_Lab2_Template/Hardware/Simulation_Source/Wrapper_tb.v"
